pipeline {
    agent any

    environment {
        HELLO = 'hello world!!'
    }

    stages {
        stage('Build') {
            steps {
                sh 'echo "${HELLO}"'

            }
        }
    }
}
