@Library('jenkins-lab') _

pipeline {
    // Run on any available Jenkins agent
    agent any
    options {
        disableConcurrentBuilds(abortPrevious: true)
    }
    stages {
        stage("Detect Changes") {
            steps {
                script {
                    def backendChanged = false
                    def frontendChanged = false
                    def changes = currentBuild.rawBuild.changeSets
                    changes.each { changeSet ->
                        changeSet.items.each { item ->
                            if (item.path.contains('backend/')) {
                                backendChanged = true
                            }
                            if (item.path.contains('frontend/')) {
                                frontendChanged = true
                            }
                        }
                    }
                    echo "Backend changed: ${backendChanged}"
                    echo "Frontend changed: ${frontendChanged}"
                    env.BACKEND_CHANGED = backendChanged
                    env.FRONTEND_CHANGED = frontendChanged

                }
            }
        }
        // Run backend and frontend tests sequentially using Docker containers
        parallel {
            stage('Backend Tests') {
                when {
                    expression { env.BACKEND_CHANGED == 'true' }
                }
                steps {
                    echo 'Running backend tests...'

                }
            }
            stage('Frontend Tests') {
                when {
                    expression { env.FRONTEND_CHANGED == 'true' }
                }
                steps {
                    echo 'Running frontend tests...'

                }
            }
        }
    }
    post {
        success {
            notifySlack(is_success: true)
        }
        failure {
            notifySlack(is_success: false)
        }
    }
}
