pipeline {
    // Run on any available Jenkins agent
    agent any
    options {
        disableConcurrentBuilds(abortPrevious: true)
    }

    stages {
        // Run backend and frontend tests sequentially using Docker containers
        stages('hello'){
            steps {
                echo 'Hello, Jenkins!'
            }
        }
    }
    post {
        success {
            slackSend message: 'Build succeeded!', color: 'good'
        }
        failure {
            slackSend message: 'Build failed!', color: 'danger'
        }
    }
}
